config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'index', to: 'users#index'
  get 'profile', to: 'users#show'
  get 'edit', to: 'users#edit'
  post 'edit', to: 'users#update'
  get 'signup', to: 'users#new'
  resources :posts do 
  	resources :comments
  end
  resources :users

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 	before_action :find_post
 	before_action :find_comment, only: [:edit,:update,:destroy]
 	before_action :authenticate_user!

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end


	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_comment
		@comment = @post.comments.find(params[:id])
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :update, :edit, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end


	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def show
	
	end
		
	def update
		if @post.update(post_params)
			redirect_to post_path
		else
			render 'edit'
		end
	end

	def edit
	
	end

	def destroy
		if @post.destroy()
			redirect_to root_path
		end
	end


	private

	def post_params
		params.require(:post).permit(:content, :user_id, :created_by, :profile_id)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :update, :edit, :destroy]
	before_action :find_post, only: [:show]

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "User Sucessfully Created!"
			redirect_to @user
		else
			flash[:alert] = "User not created"
			render 'user/index'
		end
	end

	def edit
	end




	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email)
	end

	def post_params
		params.require(:post).permit(:content, :user_id, :created_by, :profile_id)
	end

	def find_post
		@post = Post.find(params[:id])
	end

	def find_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted by: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago </p>


<% if user_signed_in? %>
	<% if comment.user_id == current_user.id %>
		<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
		<%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"} %>
	<% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comments</h1>
<%= simple_form_for([@post, @comment]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoChalle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="navbar navbar-default">
    	<div class = "container">
    		<div class = "navbar-header">
    		<%= link_to "User List", root_path, class: "navbar-brand" %>
    		</div>
    		<ul class = "nav navbar-nav">
    			<li><%= link_to "Sign Up", new_user_registration_path %></li>
    				<% if user_signed_in? %>
    				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    		<% else %>
    			<li><%= link_to "Login", new_user_session_path %></li>
    		<% end %>
    		</ul>
    		<% if user_signed_in? %>
    		<p><%= link_to "New Post", new_post_path, class: "navbar-right navbar-text navbar-link" %></p>
    		<% end %>
    	</div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Post List</h1>

<% @posts.each do |post| %>
	<%= post.content %>
	<%= link_to "View Post", post_path(post), class: "btn-custom" %>
	<br>
	<br>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.content %></h2>
<p>Posted by: <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %> ago </p>
<h3> Comments: </h3>
<%= render @post.comments %>
<p>Reply to Post
<%= render 'comments/form' %></p>
<br>

<%= link_to "Back to Post List", posts_path %>

<% if user_signed_in? %>
	<% if @post.user_id == current_user.id %>
		<%= link_to "Edit Post", edit_post_path %>
		<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete?"} %>
	<% end %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @post do |f| %>
	<%= f.input :content %>
	<%= f.button :submit %>
<% end %>

app/views/users/_profile.html.erb
<h2><%= @post.content %></h2>
<p>Posted by: <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %> ago </p>

app/views/users/index.html.erb
<h1>Hi Users</h1>
<% @users.each do |user| %>
	<%= link_to user.email, user_path(user) %>
	<br>
<% end %>
<%= link_to "Post List", posts_path %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<% if user_signed_in? %>
	<% if @user.id == current_user.id %>
		<%= link_to "Edit Registration Info", edit_user_registration_path %>
	<% end %>
<% end %>





<% if @user.email == @post.user.email %>

	<%= render 'profile' %>
	<h3> Comments: </h3>
	<%= render @post.comments %>
	<p>Reply to Post
	<%= render 'comments/form' %></p>
	<br>

<% end %>